### PR TITLE
Changes post 230901 meeting

### PR DESCRIPTION
**Pull request by W-Mohammed**

### CODE REVIEW

**Comment by RobertASmith** [comment]
Just checking as this is still blank:
image

**Comment by RobertASmith** [comment]
image

**Comment by RobertASmith** [comment]
@W-Mohammed the two issues highlighted above probably don't matter but I'm just flagging them in case.

**Comment by W-Mohammed** [comment]
Thanks @Robert Smith!
Yes, these are fine for now!
The CMD checks are yet to be addressed, and the about section is yet to be populated!

**Pull request merged**
